create table "public"."fight_types" (
    "id" integer generated by default as identity not null,
    "type" text
);


alter table "public"."fight_types" enable row level security;

create table "public"."fighting_styles" (
    "id" integer generated by default as identity not null,
    "name" text
);


alter table "public"."fighting_styles" enable row level security;

create table "public"."interaction_status" (
    "id" integer generated by default as identity not null,
    "status" text not null
);


alter table "public"."interaction_status" enable row level security;

create table "public"."interactions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "updated_by" uuid not null,
    "actor_id" uuid not null,
    "target_id" uuid not null,
    "status_id" integer not null,
    "photo_id" uuid
);


alter table "public"."interactions" enable row level security;

create table "public"."profile_fighting_styles" (
    "profile_id" uuid not null,
    "fighting_style_id" integer not null
);


alter table "public"."profile_fighting_styles" enable row level security;

create table "public"."profile_opponent_styles" (
    "profile_id" uuid not null,
    "fighting_style_id" integer not null
);


alter table "public"."profile_opponent_styles" enable row level security;

create table "public"."profile_photos" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "photo_url" text not null,
    "photo_order" integer not null,
    "active" boolean not null
);


alter table "public"."profile_photos" enable row level security;

create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "name" text,
    "date_of_birth" date,
    "height_cm" smallint,
    "weight_kg" smallint,
    "area" text,
    "latitude" double precision,
    "longitude" double precision,
    "fight_type_id" integer,
    "max_distance_km" integer default 160,
    "years_of_experience" integer default 0,
    "phone" text
);


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX fighting_styles_pkey ON public.fighting_styles USING btree (id);

CREATE UNIQUE INDEX interaction_status_pkey ON public.interaction_status USING btree (id);

CREATE UNIQUE INDEX interactions_pkey ON public.interactions USING btree (id);

CREATE UNIQUE INDEX profile_fighting_styles_pkey ON public.profile_fighting_styles USING btree (profile_id, fighting_style_id);

CREATE UNIQUE INDEX profile_opponent_styles_pkey ON public.profile_opponent_styles USING btree (profile_id, fighting_style_id);

CREATE UNIQUE INDEX profile_photos_pkey ON public.profile_photos USING btree (id);

CREATE UNIQUE INDEX profiles_phone_key ON public.profiles USING btree (phone);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX tournament_type_pkey ON public.fight_types USING btree (id);

alter table "public"."fight_types" add constraint "tournament_type_pkey" PRIMARY KEY using index "tournament_type_pkey";

alter table "public"."fighting_styles" add constraint "fighting_styles_pkey" PRIMARY KEY using index "fighting_styles_pkey";

alter table "public"."interaction_status" add constraint "interaction_status_pkey" PRIMARY KEY using index "interaction_status_pkey";

alter table "public"."interactions" add constraint "interactions_pkey" PRIMARY KEY using index "interactions_pkey";

alter table "public"."profile_fighting_styles" add constraint "profile_fighting_styles_pkey" PRIMARY KEY using index "profile_fighting_styles_pkey";

alter table "public"."profile_opponent_styles" add constraint "profile_opponent_styles_pkey" PRIMARY KEY using index "profile_opponent_styles_pkey";

alter table "public"."profile_photos" add constraint "profile_photos_pkey" PRIMARY KEY using index "profile_photos_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."interactions" add constraint "interactions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_actor_id_fkey";

alter table "public"."interactions" add constraint "interactions_photo_id_fkey" FOREIGN KEY (photo_id) REFERENCES profile_photos(id) not valid;

alter table "public"."interactions" validate constraint "interactions_photo_id_fkey";

alter table "public"."interactions" add constraint "interactions_status_id_fkey" FOREIGN KEY (status_id) REFERENCES interaction_status(id) not valid;

alter table "public"."interactions" validate constraint "interactions_status_id_fkey";

alter table "public"."interactions" add constraint "interactions_target_id_fkey" FOREIGN KEY (target_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_target_id_fkey";

alter table "public"."interactions" add constraint "interactions_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_updated_by_fkey";

alter table "public"."profile_fighting_styles" add constraint "profile_fighting_styles_fighting_style_id_fkey" FOREIGN KEY (fighting_style_id) REFERENCES fighting_styles(id) not valid;

alter table "public"."profile_fighting_styles" validate constraint "profile_fighting_styles_fighting_style_id_fkey";

alter table "public"."profile_fighting_styles" add constraint "profile_fighting_styles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_fighting_styles" validate constraint "profile_fighting_styles_profile_id_fkey";

alter table "public"."profile_opponent_styles" add constraint "profile_opponent_styles_fighting_style_id_fkey" FOREIGN KEY (fighting_style_id) REFERENCES fighting_styles(id) not valid;

alter table "public"."profile_opponent_styles" validate constraint "profile_opponent_styles_fighting_style_id_fkey";

alter table "public"."profile_opponent_styles" add constraint "profile_opponent_styles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_opponent_styles" validate constraint "profile_opponent_styles_profile_id_fkey";

alter table "public"."profile_photos" add constraint "profile_photos_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_photos" validate constraint "profile_photos_profile_id_fkey";

alter table "public"."profiles" add constraint "profiles_fight_type_id_fkey" FOREIGN KEY (fight_type_id) REFERENCES fight_types(id) not valid;

alter table "public"."profiles" validate constraint "profiles_fight_type_id_fkey";

alter table "public"."profiles" add constraint "profiles_phone_key" UNIQUE using index "profiles_phone_key";

grant delete on table "public"."fight_types" to "anon";

grant insert on table "public"."fight_types" to "anon";

grant references on table "public"."fight_types" to "anon";

grant select on table "public"."fight_types" to "anon";

grant trigger on table "public"."fight_types" to "anon";

grant truncate on table "public"."fight_types" to "anon";

grant update on table "public"."fight_types" to "anon";

grant delete on table "public"."fight_types" to "authenticated";

grant insert on table "public"."fight_types" to "authenticated";

grant references on table "public"."fight_types" to "authenticated";

grant select on table "public"."fight_types" to "authenticated";

grant trigger on table "public"."fight_types" to "authenticated";

grant truncate on table "public"."fight_types" to "authenticated";

grant update on table "public"."fight_types" to "authenticated";

grant delete on table "public"."fight_types" to "service_role";

grant insert on table "public"."fight_types" to "service_role";

grant references on table "public"."fight_types" to "service_role";

grant select on table "public"."fight_types" to "service_role";

grant trigger on table "public"."fight_types" to "service_role";

grant truncate on table "public"."fight_types" to "service_role";

grant update on table "public"."fight_types" to "service_role";

grant delete on table "public"."fighting_styles" to "anon";

grant insert on table "public"."fighting_styles" to "anon";

grant references on table "public"."fighting_styles" to "anon";

grant select on table "public"."fighting_styles" to "anon";

grant trigger on table "public"."fighting_styles" to "anon";

grant truncate on table "public"."fighting_styles" to "anon";

grant update on table "public"."fighting_styles" to "anon";

grant delete on table "public"."fighting_styles" to "authenticated";

grant insert on table "public"."fighting_styles" to "authenticated";

grant references on table "public"."fighting_styles" to "authenticated";

grant select on table "public"."fighting_styles" to "authenticated";

grant trigger on table "public"."fighting_styles" to "authenticated";

grant truncate on table "public"."fighting_styles" to "authenticated";

grant update on table "public"."fighting_styles" to "authenticated";

grant delete on table "public"."fighting_styles" to "service_role";

grant insert on table "public"."fighting_styles" to "service_role";

grant references on table "public"."fighting_styles" to "service_role";

grant select on table "public"."fighting_styles" to "service_role";

grant trigger on table "public"."fighting_styles" to "service_role";

grant truncate on table "public"."fighting_styles" to "service_role";

grant update on table "public"."fighting_styles" to "service_role";

grant delete on table "public"."interaction_status" to "anon";

grant insert on table "public"."interaction_status" to "anon";

grant references on table "public"."interaction_status" to "anon";

grant select on table "public"."interaction_status" to "anon";

grant trigger on table "public"."interaction_status" to "anon";

grant truncate on table "public"."interaction_status" to "anon";

grant update on table "public"."interaction_status" to "anon";

grant delete on table "public"."interaction_status" to "authenticated";

grant insert on table "public"."interaction_status" to "authenticated";

grant references on table "public"."interaction_status" to "authenticated";

grant select on table "public"."interaction_status" to "authenticated";

grant trigger on table "public"."interaction_status" to "authenticated";

grant truncate on table "public"."interaction_status" to "authenticated";

grant update on table "public"."interaction_status" to "authenticated";

grant delete on table "public"."interaction_status" to "service_role";

grant insert on table "public"."interaction_status" to "service_role";

grant references on table "public"."interaction_status" to "service_role";

grant select on table "public"."interaction_status" to "service_role";

grant trigger on table "public"."interaction_status" to "service_role";

grant truncate on table "public"."interaction_status" to "service_role";

grant update on table "public"."interaction_status" to "service_role";

grant delete on table "public"."interactions" to "anon";

grant insert on table "public"."interactions" to "anon";

grant references on table "public"."interactions" to "anon";

grant select on table "public"."interactions" to "anon";

grant trigger on table "public"."interactions" to "anon";

grant truncate on table "public"."interactions" to "anon";

grant update on table "public"."interactions" to "anon";

grant delete on table "public"."interactions" to "authenticated";

grant insert on table "public"."interactions" to "authenticated";

grant references on table "public"."interactions" to "authenticated";

grant select on table "public"."interactions" to "authenticated";

grant trigger on table "public"."interactions" to "authenticated";

grant truncate on table "public"."interactions" to "authenticated";

grant update on table "public"."interactions" to "authenticated";

grant delete on table "public"."interactions" to "service_role";

grant insert on table "public"."interactions" to "service_role";

grant references on table "public"."interactions" to "service_role";

grant select on table "public"."interactions" to "service_role";

grant trigger on table "public"."interactions" to "service_role";

grant truncate on table "public"."interactions" to "service_role";

grant update on table "public"."interactions" to "service_role";

grant delete on table "public"."profile_fighting_styles" to "anon";

grant insert on table "public"."profile_fighting_styles" to "anon";

grant references on table "public"."profile_fighting_styles" to "anon";

grant select on table "public"."profile_fighting_styles" to "anon";

grant trigger on table "public"."profile_fighting_styles" to "anon";

grant truncate on table "public"."profile_fighting_styles" to "anon";

grant update on table "public"."profile_fighting_styles" to "anon";

grant delete on table "public"."profile_fighting_styles" to "authenticated";

grant insert on table "public"."profile_fighting_styles" to "authenticated";

grant references on table "public"."profile_fighting_styles" to "authenticated";

grant select on table "public"."profile_fighting_styles" to "authenticated";

grant trigger on table "public"."profile_fighting_styles" to "authenticated";

grant truncate on table "public"."profile_fighting_styles" to "authenticated";

grant update on table "public"."profile_fighting_styles" to "authenticated";

grant delete on table "public"."profile_fighting_styles" to "service_role";

grant insert on table "public"."profile_fighting_styles" to "service_role";

grant references on table "public"."profile_fighting_styles" to "service_role";

grant select on table "public"."profile_fighting_styles" to "service_role";

grant trigger on table "public"."profile_fighting_styles" to "service_role";

grant truncate on table "public"."profile_fighting_styles" to "service_role";

grant update on table "public"."profile_fighting_styles" to "service_role";

grant delete on table "public"."profile_opponent_styles" to "anon";

grant insert on table "public"."profile_opponent_styles" to "anon";

grant references on table "public"."profile_opponent_styles" to "anon";

grant select on table "public"."profile_opponent_styles" to "anon";

grant trigger on table "public"."profile_opponent_styles" to "anon";

grant truncate on table "public"."profile_opponent_styles" to "anon";

grant update on table "public"."profile_opponent_styles" to "anon";

grant delete on table "public"."profile_opponent_styles" to "authenticated";

grant insert on table "public"."profile_opponent_styles" to "authenticated";

grant references on table "public"."profile_opponent_styles" to "authenticated";

grant select on table "public"."profile_opponent_styles" to "authenticated";

grant trigger on table "public"."profile_opponent_styles" to "authenticated";

grant truncate on table "public"."profile_opponent_styles" to "authenticated";

grant update on table "public"."profile_opponent_styles" to "authenticated";

grant delete on table "public"."profile_opponent_styles" to "service_role";

grant insert on table "public"."profile_opponent_styles" to "service_role";

grant references on table "public"."profile_opponent_styles" to "service_role";

grant select on table "public"."profile_opponent_styles" to "service_role";

grant trigger on table "public"."profile_opponent_styles" to "service_role";

grant truncate on table "public"."profile_opponent_styles" to "service_role";

grant update on table "public"."profile_opponent_styles" to "service_role";

grant delete on table "public"."profile_photos" to "anon";

grant insert on table "public"."profile_photos" to "anon";

grant references on table "public"."profile_photos" to "anon";

grant select on table "public"."profile_photos" to "anon";

grant trigger on table "public"."profile_photos" to "anon";

grant truncate on table "public"."profile_photos" to "anon";

grant update on table "public"."profile_photos" to "anon";

grant delete on table "public"."profile_photos" to "authenticated";

grant insert on table "public"."profile_photos" to "authenticated";

grant references on table "public"."profile_photos" to "authenticated";

grant select on table "public"."profile_photos" to "authenticated";

grant trigger on table "public"."profile_photos" to "authenticated";

grant truncate on table "public"."profile_photos" to "authenticated";

grant update on table "public"."profile_photos" to "authenticated";

grant delete on table "public"."profile_photos" to "service_role";

grant insert on table "public"."profile_photos" to "service_role";

grant references on table "public"."profile_photos" to "service_role";

grant select on table "public"."profile_photos" to "service_role";

grant trigger on table "public"."profile_photos" to "service_role";

grant truncate on table "public"."profile_photos" to "service_role";

grant update on table "public"."profile_photos" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


